<?php
/*
| Trek RPG Site Manager
| Author: Nolanator
| Version: 1.0
|
| File: settings.php
| Build x
| <Changes>
| Generated by script/Modified by the user
|
| <Purpose>
| SPMS master config file - Refer to manual for help
|
| TRSM1.0 is (c) Nolan 2003-2005, and is covered by the GPL License (See gpl.txt for more information)
*/

//	mySQL database connection settings
$host = 'localhost'; 
$user = 'tumbleweeddesign'; 
$pass = ''; 
$datab = 'trsm';

//	Ship Master Settings
$shipname = "USS Your Ship"; 
$path = "http://www.hosting.com/trsm/"; //Path to the installation 

//These are the initial superuser account settings, these are essential for getting into the system, don't make them easy to guess.
$admin_usr='admin'; 
$admin_pwd='admin'; 
//Once the system has installed, the above 2 lines can be removed

//paths to image locations
$ipath = "images/";
$rpath = "images/ranks/";
$awdpath = "images/awards/";

//path to Css Files
$csspath = "css/";

//What admins get copies of the join applications, based on admin level.
$email_level = 5;

//Options - what sections to install, and show on menu
$mod_specs = true;
$mod_forums = true;
$mod_missions = true;
$mod_report = true;
$mod_awards = true;
$mod_records = true;
$mod_coc = true;
$mod_database = true;

//###############
// Custom bios box sizes (=p)
//###############
$line_size = "20";
$box_cols = "25";
$box_rows = "3";
$linesmall_size = "4";
$linemed_size = "15";
$boxlarge_cols = "35";
$boxlarge_rows = "6";

//###############
//Posting Report Settings
//###############
/*
  --Time period Options--
  This Week
  Two Weeks
  Last Month
  Last Week
  This Month
  OR
  any date, and all posts since that date will be counted
*/
$time_period1 = 'This Week';
$time_period2 = 'Two Weeks';
$time_period3 = 'Last Month';

$first_day = 'Sunday';
$show_synop = true;
$remove_posts = false; //Should the system remove all posts when a player is removed? true/false
$display_limit = 20; //How many posts to view per page

//###############
//Awards System Settings
//###############
//Should the system delete all awards by a member when they leave? true/false
$remove_awards = false;

//###############
//Document Juggler Stuff
//###############
// 
 # application name
 $DJ_appname = $shipname . ' Database';
    
//###############
//miniBB settings, alter after this line at own risk (its setup as per default install folders)
//###############
/*
Options for miniBB. Alter with care.
Copyright (C) 2001-2003 miniBB.net.
*/

$admin_email='superuser@spms';
$lang='eng';
$skin='default';
$sitename= $shipname . ' :: Forums';
$emailadmin=0;
$emailusers=1;
$userRegName='_A-Za-z0-9 ';
$l_sepr = '&middot;';

$post_text_maxlength=10240;
$post_word_maxlength=70;
$topic_max_length=50;
$viewmaxtopic=30;
$viewlastdiscussions=30;
$viewmaxreplys=30;
$viewmaxsearch=30;
$viewpagelim=50;
$viewTopicsIfOnlyOneForum=0;

$protectWholeForum=0;
$protectWholeForumPwd='pwd';

$postRange=60;

$dateFormat='MM DD, YYYY<br>T';

/* New options for miniBB 1.1 */
$disallowNames=array('Anonymous');
/* New options for miniBB 1.2 */
$sortingTopics=0;
$topStats=4;
$genEmailDisable=0;
/* New options for miniBB 1.3 */
$defDays=365;
$userUnlock=0;
/* New options for miniBB 1.5 */
$emailadmposts=0;
$useredit=86400; 
/* New options for miniBB 1.7 */
$stats_barWidthLim='31';

//###############
//Table Names
//###############

$table['forums'] = 'minibb_forums';
$table['forum_posts'] = 'minibb_posts';
$table['topics'] = 'minibb_topics';
$table['send_emails'] = 'minibb_send_mails';
$table['forum_banned'] = 'minibb_banned';

$table['users'] = 'minibb_users';
$table['crew'] = 'crew';
$table['ranks'] = 'ranks';
$table['positions'] = 'positions';
$table['departments'] = 'departments';
$table['customfields'] = 'customfields';
$table['biodata'] = 'biodata';
$table['awards'] = 'awards';
$table['awarded'] = 'awarded';
$table['missions'] = 'missions';
$table['news'] = 'news';
$table['points'] = 'points';
$table['posts'] = 'posts';
$table['records'] = 'records';
$table['specs'] = 'specifications';
$table['styles'] = 'styles';

//###############
//Misc Stuff / 3rd Party Settings, don't touch me please! (If you do...you really really need to know what yer doing)
//###############

//Minibb
$DB='mysql';
$DBhost = $host;
$DBname = $datab;
$DBusr = $user;
$DBpwd = $pass;
$bb_admin='bb_admin.php';
$main_url = $path . '/forum';
$indexphp='forum.php?';
//Cookie Options, also used by spms logins
$cookiedomain = '';
$cookiename='miniBBsite';
$cookiepath='/';
//$cookiepath = $path;
$cookiesecure=FALSE;
$cookie_expires=90000;
$cookie_renew=1800;
$cookielang_exp=2592000;
//Minibb Tables
$Tf=$table['forums'];
$Tp=$table['forum_posts'];
$Tt=$table['topics'];
$Tu=$table['users'];
$Ts=$table['send_emails'];
$Tb=$table['forum_banned'];

//Doc Juggler
$DJ_host = $host;
$DJ_database = $datab;
$DJ_user = $user;
$DJ_password = $pass;
$DJ_path = $path;
$DJ_file = 'database.php';

//Build image path
$imagepath = $path . $ipath;
?>